services:
  postgres-db:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  authentication:
    image: authentication:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./authentication
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - APPLICATION_PORT=8080
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./logs/authentication/:/var/log/authentication

  logger:
    image: logger:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./logger
    environment:
      - APPLICATION_PORT=8020
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
    deploy:
      replicas: 1
    ports:
      - "8020:8020"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./logs/logger/:/var/log/logger

  task:
    image: task:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./task
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - APPLICATION_PORT=8060
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - JWT_ISSUER_URI=http://localhost:8080
      - JWK_SET_URI=http://host.docker.internal:8080/authentication/jwks
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    deploy:
      replicas: 1
    ports:
      - "8060:8060"
    depends_on:
      postgres-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs/task/:/var/log/task

  notification:
    image: notification:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./notification
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - APPLICATION_PORT=8050
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - FAKE_SMTP_SERVER=fake-smtp-server
      - FAKE_SMTP_PORT=8025
    deploy:
      replicas: 1
    ports:
      - "8050:8050"
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs/notification/:/var/log/notification

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbit-data:/var/lib/rabbitmq/mnesia/"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 30000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 30000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.request.logger=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_CREATE_TOPICS: "log-message:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: kafka
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  fake-smtp-server:
    image: gessnerfl/fake-smtp-server:latest
    ports:
      - "8025:8025"      #expose smtp port
      - "5555:8080"      #expose web ui
      - "8081:8081"      #expose management api
