spring:
  application:
    name: task
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA:public}&search_path==${POSTGRES_SCHEMA:public}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: log-group
    producer:
      retries: 5
      properties:
        retry.backoff.ms: 1000

kafka-topic: log-message

server:
  port: ${APPLICATION_PORT:8060}
  servlet:
    context-path: "/task"

logging:
  file:
    path: /var/log/task